{{- if and (eq .Values.ingress.expose true) (eq .Values.ingress.secure false) -}}
{{- $serviceName := default (include "cava-media.name" .) -}}
{{- $servicePort := .Values.service.port -}}
{{- $servicePath := .Values.path -}}
# https://doc.traefik.io/traefik/providers/kubernetes-crd/#letsencrypt-support-with-the-custom-resource-definition-provider
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "cava-media.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ $servicePath }}`)
      kind: Rule
      services:
        - name: {{ $serviceName }}
          port: {{ $servicePort }}
{{- end -}}