# Default values for cava-media.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: cava-media
# fullnameOverride: cava-media
path: /media
service:
  targetPort: 8080
  portName: http
  type: ClusterIP
  port: 80
  containerPort: 8080
  servicePortName: http
image:
  repository: cormorack/cava-media
  tag: "set-by-chartpress"
  pullSecrets: []
  pullPolicy: Always
replicas: 1
resources: {}
env:
  - name: WPUSER
    value: ""
  - name: WPPASSWORD
    value: ""
  - name: USERNAME
    value: ""
  - name: PASSWORD
    value: ""
  - name: HOST
    value: ""
  - name: PORT
    value: ""
  - name: DBNAME
    value: ""
  - name: MAXFILESIZE
    value: ""
  - name: JVM_OPTS
    value: ""
  - name: SERVER_URL
    value: ""
  - name: ISSUES
    value: ""
  - name: DATA_URL
    value: ""
  - name: QUERY
    value: ""
  - name: FEEDBACK_HOST
    value: ""

# For production deployment in k8s,
# QUERY should have the `enabledTLSProtocols`
# query variable with value of `TLSv1.2`.
# e.g. ?enabledTLSProtocols=TLSv1.2
# See: https://tinyurl.com/2vrcb53x

restartPolicy: Always
nodeSelector: {}
ingress:
  expose: false

  # If secure, must provide tls
  secure: false

  # Adds tls for domain certification
  # tls:
  #   certResolver: DEVELOPMENT
  tls: {}
